- name: Create brick directory
  file:
    dest: "/bricks/brick1/brick{{ volume_appendix }}"
    state: directory

- name: Initialize fact for list of minions
  set_fact:
    host_brick_string: "{{ hostvars[inventory_hostname]['ansible_host'] }}:/bricks/brick1/brick{{ volume_appendix }} "
    number_hosts: "{{ ( groups['minions'] | length ) + 1 }}"

- name: Loop through and create "host:/brick/" string given list of minions
  set_fact:
    host_brick_string: "{{ host_brick_string }}{{ hostvars[item]['ansible_host'] }}:/bricks/brick1/brick{{ volume_appendix }} "
  with_items: "{{ groups['minions'] }}"

# - name: Debug list of gluster volume hosts
#   debug: "msg={{host_brick_string}}"

# - name: Debug number of replicas
#   debug: "msg={{number_hosts}}"

- name: Get list of gluster volumes
  shell: >
    gluster volume list
  register: volume_list
- name: Create gluster volume name
  set_fact:
    gluster_volume_name : "glustervol{{ volume_appendix }}"

- name: Create glusterFS volume
  shell: >
    gluster volume create {{ gluster_volume_name }} replica {{ number_hosts }} transport tcp {{ host_brick_string }}
  when: '"gluster_volume_name" not in "volume_list.stdout"'

- name: Get status of volume
  shell: >
    gluster volume status {{ gluster_volume_name }}
  register: volume_status
  ignore_errors: yes

- name: Start gluster volume
  shell: >
    gluster volume start {{ gluster_volume_name }}
  when: "volume_status.rc != 0"
